### ISSUE TITLE
Help: Swashbuckle.Annotations v1.0.0 license

### ISSUE THREAD

**Issue by susan12468** [DavidDeSloovere/DavidDeSloovere#1]
Mr.Sloovere, 
 I am a developer in SAP Concur. I need your help. The Swashbuckle.Annotations v1.0.0 is currently used in one of our projects. 
However, the URL https://github.com/DaviIdDeSloovere/Swashbuckle.Annotations/blob/master/LICENSE is not found. 
Could you help me out? 

Thanks
Susan

**Comment by DavidDeSloovere** [comment]
Are you a bot?
You "mistyped" the url.
